[pytest]
markers=                    # Metadata for your report (Optional but looks professional)
         regression: marks tests as regression
         smoke: marks tests as smoke
         sanity: marks tests as sanity


# addopts = Add your favorite flags here to minimize at the CLI  while execution
# -v: Verbose
# -s: See print statements
# --capture=tee-sys: Your favorite log-viewer flag
# --self-contained-html: Keep the report clean
addopts = -v
          --capture=tee-sys
          --self-contained-html

# This tells Pytest which folders to look into
testpaths = testCases

# This helps Pytest find your test files if you name them differently
python_files = test_*.py
python_classes = Test_*
python_functions = test_*
